sudo: false

language: python

python:
  - 3.6
  - "3.7-dev"

install:
  - pip install coveralls
  - pip install -r ./requirements/pipenv.txt
  - pipenv install

script:
  - coverage run --source=mirage_test setup.py test

after_success:
  - coveralls
