sudo: false

language: python

python:
  - 3.5
  - 3.6

install:
  - pip install coveralls
  - pip install -r ./requirements/pipenv.txt
  - pipenv --three
  - pipenv install

script:
  - coverage run --source=djconsole_test setup.py test

after_success:
  - coveralls
