sudo: false

language: python

python:
  - 3.5
  - 3.6

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=djconsole_test setup.py test

after_success:
  - coveralls
